### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by btmxh** [btmxh/nrs-impl#3]
Mobile devices can't run these build tasks and python scripts lol, they'll need an app or something to run this.

Using GitHub workflows is a good way to keep the JSON files up-to-date, and the only thing left is to sync with MAL and AniList. This can be carried out using these mobile devices, in the form of an app.

**Comment by ngoduyanh** [comment]
#4

**Comment by ngoduyanh** [comment]
The GitHub workflow part is done: #4

**Comment by ngoduyanh** [comment]
The app is partially done as well: [nrs_app](https://github.com/ngoduyanh/nrs_app)

**Comment by ngoduyanh** [comment]
The mobile workflow is pretty good, but it's very inconvenient (mobile devices suck). A suggestion is introducing a library that could parse the NRS code, and automatically increment the episode count, as well as doing other things like adding standard (or even non standard) impacts/relations (inspired by cargo's `cargo add`)

**Comment by btmxh** [comment]
idc about phones i'm on pc/laptop 24/24 anyways
