### ISSUE TITLE
[RANK] Leah Kate Trilogy + mashups

### ISSUE THREAD

**Issue by btmxh** [btmxh/nrs-impl#363]
Type: Music

Life Sux (Sped Up Ver.): https://osu.ppy.sh/beatmapsets/1905234#osu/3928577  
Twinkle Twinkle (Sped Up & Cut Ver.): https://osu.ppy.sh/beatmapsets/1901049#osu/3919008
10 Things I Hate About You (Sped Up & Cut Ver.): https://osu.ppy.sh/beatmapsets/1881428#osu/3873445

10 Things I Hate About Mou Ii Kai?: https://osu.ppy.sh/beatmapsets/1927781#osu/3981047
10 Things I Hate About 哀の隙間: https://osu.ppy.sh/beatmapsets/1919786#osu/3963421  
10 Things I Hate About Sidetracked Day: https://osu.ppy.sh/beatmapsets/1925740#osu/3976296
10 Things I Hate About UNITED (Cut Ver.): https://osu.ppy.sh/beatmapsets/1927792#osu/3981075

**Comment by ngoduyanh** [comment]
THESE SONGS ARE UNDERRATED 🔥🔥🔥 LET'S KEEP THEM UNRANKED 🔥🔥🔥🔥
