### ISSUE TITLE
[RANK] Spring 2023

### ISSUE THREAD

**Issue by btmxh** [btmxh/nrs-impl#417]
Type: Anime

anime list is in my alt on AniList: https://anilist.co/user/gbnam8/animelist

**Comment by ngoduyanh** [comment]
after stablization, there are just about 8 anime:
https://anilist.co/anime/127550/Kuma-Kuma-Kuma-Bear-Punch/
https://anilist.co/anime/150672/Oshi-no-Ko/
https://anilist.co/anime/144188/Alice-Gear-Aegis-Expansion/
https://anilist.co/anime/157198/Dead-Mount-Death-Play/
https://anilist.co/anime/131518/Dr-STONE-NEW-WORLD/
https://anilist.co/anime/134131/Mahou-Shoujo-Magical-Destroyers/
https://anilist.co/anime/151189/My-Home-Hero/
https://anilist.co/anime/146975/THE-iDOLMSTER-Cinderella-Girls-U149/

**Comment by ngoduyanh** [comment]
notable ops:
~Idol - YOASOBI~ (soulless meme song)
Shine In The Sky☆ - U149 (:sob: :sob: :sob: god please kill these localists how are they still alive pogpega same composer as dech ai nhu nhat minh dech ai nhu the king clematis)
Dash and Go - Aina Suzuki (L bozo tranny keep crying and sucking lantis' cock)
Magical Destroyers - Aimi (lmfao more lantis cocksucking for the tranny himself, poor soul)

**Comment by btmxh** [comment]
done ig
